<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_more_vert (3)</name>
   <tag></tag>
   <elementGuidId>f15c2078-950c-48e4-b905-d1fbc04c84aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mis-materias']/div[2]/div[8]/div/mat-card[2]/div[2]/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-tooltip-trigger.mat-menu-trigger.options.custom-button.z-index-up__cdk.mat-icon-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5330e214-9fbd-4168-80c2-6c945b153c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a7671fc5-f33b-4a28-bbae-d4be237364f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltipposition</name>
      <type>Main</type>
      <value>below</value>
      <webElementGuid>dc973351-ef58-4602-9e6d-4e06f6b968cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-tooltip-trigger mat-menu-trigger options custom-button z-index-up__cdk mat-icon-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>9e21788a-e55c-4677-93db-b7af088dfba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Opciones</value>
      <webElementGuid>f2b36699-4d93-4597-b59f-7d0b8722789b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>d0a2b4f9-71f4-40f5-9e4a-d62ed3db2094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mis-materias&quot;)/div[@class=&quot;d-flex materia-container ng-star-inserted&quot;]/div[@class=&quot;materia d-flex flex-column justify-content-between route-animations-elements verdeCN ng-star-inserted&quot;]/div[@class=&quot;card-inner flipped&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator card-back custom-bg__dark d-flex flex-column px-0 pb-2 pt-0&quot;]/div[@class=&quot;card-back__container&quot;]/div[@class=&quot;libros py-1 custom-border__regular d-flex justify-content-between align-items-center w-100 ng-star-inserted&quot;]/div[@class=&quot;actions-menu z-index-up__cdk&quot;]/button[@class=&quot;mat-focus-indicator mat-tooltip-trigger mat-menu-trigger options custom-button z-index-up__cdk mat-icon-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>5e1e5173-752b-4efa-9cb6-fcc312d3c513</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mis-materias']/div[2]/div[8]/div/mat-card[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>7a538ac0-57de-42c5-85ed-5d9961511935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libro_Profesor_estres_1'])[1]/following::button[1]</value>
      <webElementGuid>622cec26-124c-4d5c-b73b-949c4285de70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[2]/following::button[2]</value>
      <webElementGuid>2391dfab-a95c-4116-b476-6f7b04494130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[3]/preceding::button[1]</value>
      <webElementGuid>39b742ff-ed37-4ca6-adf9-e68f45ccda03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[4]/preceding::button[1]</value>
      <webElementGuid>e9015639-b640-43ac-b600-47f4e53f2c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>bd0c338b-65fc-47b2-b815-ac04f91ee2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>29fb84f9-7882-4449-9a6a-865819394f04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
