<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_more_vert (1)</name>
   <tag></tag>
   <elementGuidId>dfce760a-e0f2-439c-bbef-c1980b60b56e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mis-materias']/div[2]/div[8]/div/mat-card[2]/div[2]/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-tooltip-trigger.mat-menu-trigger.options.custom-button.z-index-up__cdk.mat-icon-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc51aeea-d448-458f-aea6-ff98f5c9dd63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>78257d50-7c21-4882-92e5-bc64b8725d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltipposition</name>
      <type>Main</type>
      <value>below</value>
      <webElementGuid>4d2457f1-ffe7-4d94-ae85-5fbe45c8ceb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-tooltip-trigger mat-menu-trigger options custom-button z-index-up__cdk mat-icon-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>1146726f-8f70-401f-a9ad-e094583884a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Opciones</value>
      <webElementGuid>68ccc954-dee2-4cc9-be83-366d2b19dcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>a36c3fbe-1459-4ae6-badc-171965909260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mis-materias&quot;)/div[@class=&quot;d-flex materia-container ng-star-inserted&quot;]/div[@class=&quot;materia d-flex flex-column justify-content-between route-animations-elements verdeCN ng-star-inserted&quot;]/div[@class=&quot;card-inner flipped&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator card-back custom-bg__dark d-flex flex-column px-0 pb-2 pt-0&quot;]/div[@class=&quot;card-back__container&quot;]/div[@class=&quot;libros py-1 custom-border__regular d-flex justify-content-between align-items-center w-100 ng-star-inserted&quot;]/div[@class=&quot;actions-menu z-index-up__cdk&quot;]/button[@class=&quot;mat-focus-indicator mat-tooltip-trigger mat-menu-trigger options custom-button z-index-up__cdk mat-icon-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>298156f6-0a3b-4aa9-abdb-8b967ede3784</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mis-materias']/div[2]/div[8]/div/mat-card[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>449e7af7-7383-4b5e-bb86-df2836a65485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[2]/following::button[2]</value>
      <webElementGuid>c7c45ce8-08d5-4189-9a1c-fb6e33740d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[1]/following::button[2]</value>
      <webElementGuid>00ff08fd-2e8e-49a9-b86e-bb6a8b8986f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[3]/preceding::button[1]</value>
      <webElementGuid>4abb6fcc-701b-49c3-861b-f2b02a35ba34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[4]/preceding::button[1]</value>
      <webElementGuid>50720698-a412-4ebd-956f-d8cf19382d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>df84b717-b408-47a3-9559-a3e7f722aaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>daa9b80b-113d-431a-a65a-f663867988cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
