<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aceptar</name>
   <tag></tag>
   <elementGuidId>01adfa79-3e84-4142-ba45-5ed6e6d3933b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.default-button.default-button__primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;dialog-reasignar-grupo&quot;]/div[3]/button[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@role = 'button' and @type = 'button' and @class = 'default-button default-button__primary' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6d13311f-10d5-4543-890e-9abb8e0d1d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cb1d91f6-2b3c-4c52-9068-0b71a9aa8f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86296adc-8ce1-44db-87dd-d83d05b03cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default-button default-button__primary</value>
      <webElementGuid>2987ec3e-6a48-46a0-a824-e2a01e763778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>a8edfbe0-58a8-4114-a67a-bd06b8f7196c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=&quot;dialog-reasignar-grupo&quot;]/div[3]/button[2]</value>
      <webElementGuid>f6ca0f94-4356-426f-b81c-bd9434fb31ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
