<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_more_vert (4)</name>
   <tag></tag>
   <elementGuidId>35cb2579-2a44-4c4e-8750-34c2498a5e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mis-materias']/div[2]/div[8]/div/mat-card[2]/div[2]/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-tooltip-trigger.mat-menu-trigger.options.custom-button.z-index-up__cdk.mat-icon-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d466abc-9f23-4e4e-831a-0921e71d5aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0dab9eb6-c3b0-42cc-b17c-f1ed259996cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltipposition</name>
      <type>Main</type>
      <value>below</value>
      <webElementGuid>3cde605c-a0bf-4c95-8300-5d2ebe24e38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-tooltip-trigger mat-menu-trigger options custom-button z-index-up__cdk mat-icon-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>11920168-7fb7-4173-86bb-ee779897dd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Opciones</value>
      <webElementGuid>05117b7f-6577-4a62-8754-4289be13ff35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>03449d20-8766-4676-b3c8-715919f246f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mis-materias&quot;)/div[@class=&quot;d-flex materia-container ng-star-inserted&quot;]/div[@class=&quot;materia d-flex flex-column justify-content-between route-animations-elements verdeCN ng-star-inserted&quot;]/div[@class=&quot;card-inner&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator card-back custom-bg__dark d-flex flex-column px-0 pb-2 pt-0&quot;]/div[@class=&quot;card-back__container&quot;]/div[@class=&quot;libros py-1 custom-border__regular d-flex justify-content-between align-items-center w-100 ng-star-inserted&quot;]/div[@class=&quot;actions-menu z-index-up__cdk&quot;]/button[@class=&quot;mat-focus-indicator mat-tooltip-trigger mat-menu-trigger options custom-button z-index-up__cdk mat-icon-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>e0866f8b-bf78-4f27-a8e0-0dfcfbe3a59f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mis-materias']/div[2]/div[8]/div/mat-card[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>620f1b7b-6447-420e-9d11-49671d67c3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libro_Profesor_estres_1'])[1]/following::button[1]</value>
      <webElementGuid>15157c45-0d95-4879-b0ed-095ba695ae33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[2]/following::button[2]</value>
      <webElementGuid>465afff9-ad31-4d38-91e3-9e10a342c1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[3]/preceding::button[1]</value>
      <webElementGuid>6ffb661b-0ede-4be8-a90e-bf42685be74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[4]/preceding::button[1]</value>
      <webElementGuid>554c73de-6062-4eaf-a69b-8a0b1cf96fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>5b2a28a5-33c7-49d7-a6bb-5f6e8449137b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>928e6c45-dcdc-4740-9184-1180a4283df3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
