<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Entrar (1)</name>
   <tag></tag>
   <elementGuidId>a3700c1f-9c7c-412d-9a2c-e93aad865da4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.w-100.default-button.default-button__secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>306a6d95-cc73-47b9-85c2-88b92a2003f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df7bbc61-88da-4dc8-953e-9b2a216f6d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2a84659a-4ad0-45a5-90b4-f688679cc9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 default-button default-button__secondary</value>
      <webElementGuid>77a5d793-cb11-4aa6-b879-288028ed3012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entrar</value>
      <webElementGuid>7c325807-905d-421a-902f-6077650455c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/aula-planeta-root[@class=&quot;ng-tns-c231-0&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;default-theme login-page ng-star-inserted&quot;]/div[@class=&quot;data-container d-flex flex-column justify-content-start justify-content-sm-center&quot;]/div[@class=&quot;login-container d-flex flex-row&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/form[@class=&quot;d-flex flex-column ng-dirty ng-touched ng-valid&quot;]/fieldset[@class=&quot;d-flex flex-column mb-4&quot;]/div[@class=&quot;d-flex&quot;]/button[@class=&quot;w-100 default-button default-button__secondary&quot;]</value>
      <webElementGuid>44202c4d-3298-46bc-966f-1db550b9d5d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>c68beaa2-819b-4b94-b99a-b3db5bc05cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear cuenta'])[1]/following::button[1]</value>
      <webElementGuid>0eaf5aab-b18d-4406-850a-35753cf220f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Has olvidado tu contraseña?'])[1]/following::button[2]</value>
      <webElementGuid>0031ef4e-ca50-43d5-95f1-e4ace230fac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar sesión'])[2]/preceding::button[1]</value>
      <webElementGuid>12737007-567b-4b48-99b5-ed0d3e9c1c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrar con Office 365'])[1]/preceding::button[1]</value>
      <webElementGuid>6726e53e-1302-4cea-9211-eca897854fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrar']/parent::*</value>
      <webElementGuid>85520c97-11fe-4dfe-ab99-c4c50105398d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>b6b84ea6-78f4-478f-a512-e5a9185dc63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Entrar' or . = 'Entrar')]</value>
      <webElementGuid>00633855-706e-4d83-99a9-8068335b7e7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
