<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_more_vert (6)</name>
   <tag></tag>
   <elementGuidId>c371957c-0f68-4a92-b09d-d5ff47bfc237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mis-materias']/div[2]/div[8]/div/mat-card[2]/div[2]/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-tooltip-trigger.mat-menu-trigger.options.custom-button.z-index-up__cdk.mat-icon-button.mat-button-base.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>969f191a-121b-4391-98c3-a2b990c2aff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>379e6ffe-bb35-4b0d-aaa2-0dfefdba03cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mattooltipposition</name>
      <type>Main</type>
      <value>below</value>
      <webElementGuid>f9e7dd70-5ec1-430b-bbfd-9c6ece207132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-tooltip-trigger mat-menu-trigger options custom-button z-index-up__cdk mat-icon-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>16c724c3-ed79-4a5e-9bd2-870722b369e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Opciones</value>
      <webElementGuid>b1ae4fbb-f551-4cfc-9c6c-07bc9d1cb62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>c122b3ed-b74a-4a90-abc1-633e23920454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mis-materias&quot;)/div[@class=&quot;d-flex materia-container ng-star-inserted&quot;]/div[@class=&quot;materia d-flex flex-column justify-content-between route-animations-elements verdeCN ng-star-inserted&quot;]/div[@class=&quot;card-inner&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator card-back custom-bg__dark d-flex flex-column px-0 pb-2 pt-0&quot;]/div[@class=&quot;card-back__container&quot;]/div[@class=&quot;libros py-1 custom-border__regular d-flex justify-content-between align-items-center w-100 ng-star-inserted&quot;]/div[@class=&quot;actions-menu z-index-up__cdk&quot;]/button[@class=&quot;mat-focus-indicator mat-tooltip-trigger mat-menu-trigger options custom-button z-index-up__cdk mat-icon-button mat-button-base cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>241a4a4a-c516-4e16-a9d4-08bdefd3b0ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mis-materias']/div[2]/div[8]/div/mat-card[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>5bb8ba70-1717-408d-981c-4e44eaad7b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Libro_Profesor_estres_1'])[1]/following::button[1]</value>
      <webElementGuid>41f78902-8367-4f90-9e4a-464e1e231099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[2]/following::button[2]</value>
      <webElementGuid>2f75f88e-8e54-44d4-82bf-9e79ef6086fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[3]/preceding::button[1]</value>
      <webElementGuid>e921121c-c6c9-4d22-bfe1-bb1265623312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciencias de la naturaleza'])[4]/preceding::button[1]</value>
      <webElementGuid>e9924a29-191d-42e9-b384-dbff5df60fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>b948c68a-81a9-435a-8ac8-18ee4b1c73db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>07132712-0130-4732-a9dd-63e354890d90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
