<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CancelarAceptar</name>
   <tag></tag>
   <elementGuidId>4cbdfd2b-7507-4a52-80ab-5cfd5420093d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dialog-reasignar-grupo']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-dialog-actions.justify-content-start.mt-2.mb-0.pb-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7cc607f-3af3-4b9f-be2e-d9a4290e79f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-actions justify-content-start mt-2 mb-0 pb-0</value>
      <webElementGuid>143ff76f-5e4d-4122-9399-db501f42c655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CancelarAceptar</value>
      <webElementGuid>5c97d60b-f45f-4753-bf5a-1c7114a2006a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-reasignar-grupo&quot;)/div[@class=&quot;mat-dialog-actions justify-content-start mt-2 mb-0 pb-0&quot;]</value>
      <webElementGuid>089f06de-f96e-44a3-b212-dd123785c893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-reasignar-grupo']/div[3]</value>
      <webElementGuid>a52735c0-2bac-4d33-b752-7b6802001b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asignación'])[1]/following::div[31]</value>
      <webElementGuid>0eae240e-803f-473a-acc6-d7634dd90757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clases'])[1]/following::div[31]</value>
      <webElementGuid>7dd6ea63-185a-4d0d-8da3-59f0e402fc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aula-planeta-reasignar-grupo/div/div[3]</value>
      <webElementGuid>5391cb63-30cb-41d2-b5df-6f9aa36dbbec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CancelarAceptar' or . = 'CancelarAceptar')]</value>
      <webElementGuid>e2d0dbab-87a4-4b1e-9976-a0b09856f0b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
