<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrasea_form-control ng-untouched n_70290b</name>
   <tag></tag>
   <elementGuidId>86a7f138-7005-4f06-931d-5924e39d1a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ng-untouched.ng-dirty.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>248d349f-a5d1-4659-8d53-62ca0c5eb2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ffc79323-048d-4413-86da-0172a2657bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>d204a5b2-7d02-4112-905f-e6540cab2725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>82ad7256-c139-4d2e-a57f-d6733348e1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>e1191428-dbd4-48fc-893e-4398e7ead686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/aula-planeta-root[@class=&quot;ng-tns-c231-0&quot;]/ng-component[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;default-theme login-page ng-star-inserted&quot;]/div[@class=&quot;data-container d-flex flex-column justify-content-start justify-content-sm-center&quot;]/div[@class=&quot;login-container d-flex flex-row&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/form[@class=&quot;d-flex flex-column ng-dirty ng-touched ng-valid&quot;]/fieldset[@class=&quot;d-flex flex-column mb-4&quot;]/div[@class=&quot;form-group w-100 default-input position-relative text-left&quot;]/input[@class=&quot;form-control ng-untouched ng-dirty ng-valid&quot;]</value>
      <webElementGuid>6b31687f-d4fb-4aed-ac65-56a954b4cd92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>00150709-5da2-4568-a467-9e931404b179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b0fd412d-5c65-4949-a85b-281e667e01ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Contraseña']</value>
      <webElementGuid>774b12f2-77e2-48fd-a7c1-7e86c733b1d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
