<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Asignar gruposSelecciona las clases</name>
   <tag></tag>
   <elementGuidId>b5e7a484-655e-42ca-94e4-ad67900beaa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>c24fd637-933b-4576-ac09-19810a79e118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d6060e76-27dc-4aa1-8507-8492ee8206ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1bc1b96-4efc-4a2f-82af-20848640e552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c113-17 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>3edc25d9-0b1b-4f1c-918d-8dde2befda34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-0</value>
      <webElementGuid>3d949759-569f-44d0-b1a0-aebb204657a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>11c5f6b9-0a48-4098-993f-b4e26cd11e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-0</value>
      <webElementGuid>12813150-db5f-483a-a390-d07026be7676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar</value>
      <webElementGuid>e5abc27a-923b-498f-bb0f-e93206a2c1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)</value>
      <webElementGuid>6f15ff74-d641-4dbb-a7f3-2c065d8c4ada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      <webElementGuid>37736e86-f9ca-4022-8c3a-7fa06becae74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/mat-dialog-container</value>
      <webElementGuid>f5d2ec40-a14d-4402-aad7-a5ef041b55b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conoce el entorno de aprendizaje'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>2a4e78bc-bccb-41c1-941d-2ba7b109cbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumnado'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>ee070adc-2150-40ef-9f20-d2f63bdba09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>afdf71c0-528b-4335-ba89-f0122c37b287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-0' and (text() = 'Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar' or . = 'Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar')]</value>
      <webElementGuid>9c285c65-8a96-47ec-b2d6-d5f3376cade0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
