<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-dialog-container_Asignar gruposSelecciona las clases (1)</name>
   <tag></tag>
   <elementGuidId>7e2b5870-6935-446d-9814-be50e6b38e73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-dialog-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-dialog-container</value>
      <webElementGuid>7739b374-f890-4469-8353-afcffb191802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c3c5161d-256d-4ae1-9802-94f1b523d5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63ef5284-8e14-4936-9bae-fc9b780ec361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-dialog-container ng-tns-c113-19 ng-trigger ng-trigger-dialogContainer ng-star-inserted</value>
      <webElementGuid>8e7cd3db-bb14-4142-8717-a9582f6a1552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-dialog-0</value>
      <webElementGuid>0a3cabb3-817a-4074-8f80-aaed47cc9128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>5e924688-c14b-455d-a653-dc76c6684563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>mat-dialog-title-0</value>
      <webElementGuid>9a8d6889-52aa-4771-946a-2ba406816d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar</value>
      <webElementGuid>c2ed9c74-9053-4ddb-bec1-c949d0d66029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)</value>
      <webElementGuid>596c4926-ca9c-4a21-8870-f3fc7777f5da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']</value>
      <webElementGuid>a14bacf6-9e3c-4f09-8b92-90a7ae866a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/mat-dialog-container</value>
      <webElementGuid>ee0c4d9f-4088-4c3a-8c19-c1059612b080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conoce el entorno de aprendizaje'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>e733ee2c-fe11-485d-98e4-e4300e5a51fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumnado'])[1]/following::mat-dialog-container[1]</value>
      <webElementGuid>1363af50-af9d-42b7-a7d1-d306c79ffda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-container</value>
      <webElementGuid>268bb006-ab17-448b-aafb-eb940df416c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id = 'mat-dialog-0' and (text() = 'Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar' or . = 'Asignar gruposSelecciona las clases o grupos a los que quieras asignar la materia personalizada: Libro_Profesor_estres_1 Clases  Asignación 5 PRI A 5 PRI B 5 PRI C 5 PRI D 5 PRI E CancelarAceptar')]</value>
      <webElementGuid>cf7576b4-9a9a-4e2d-b530-8633baebdee5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
