<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_30_Esquema</name>
   <tag></tag>
   <elementGuidId>50e15290-ac0e-4533-8d74-40ddc2738b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#roundbutton_16 > #textButtonContainer > tbody > tr > td > #realContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;image_30&quot;]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab4c6232-d45e-4f5f-979b-e0fd4cf5edc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>realContent</value>
      <webElementGuid>1c844c0f-aeb6-4915-bba6-9ab10085492b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Esquema del ciclo del agua</value>
      <webElementGuid>3d2eeead-3883-4e35-9a0d-1a0c3bda91ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roundbutton_16&quot;)/table[@id=&quot;textButtonContainer&quot;]/tbody[1]/tr[1]/td[1]/div[@id=&quot;realContent&quot;]</value>
      <webElementGuid>6634337b-11c5-492f-81e6-83912b120c7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id=&quot;image_30&quot;]/img</value>
      <webElementGuid>ebb27c84-a350-4d56-a631-d52b360c486c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
