<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Copia profesor 1</name>
   <tag></tag>
   <elementGuidId>5336f085-4084-459f-965d-16d8d0ef72fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/aula-planeta-root/aula-planeta-main/div/div/div[1]/mat-sidenav-container/mat-sidenav-content/aula-planeta-materia/div/div[2]/aula-planeta-mis-temas/table/tbody/tr[13]/td[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'Copia profesor 1' or . = 'Copia profesor 1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>88d99833-e2c5-4d87-a2c9-18fa25defb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c361-4</value>
      <webElementGuid>3c761024-ac79-47d1-8f5a-2d90fad7a858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copia profesor 1</value>
      <webElementGuid>9fd773b8-bf9f-4257-b142-ad66e6737d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-0&quot;)/tbody[1]/tr[@class=&quot;mat-row cdk-row cdk-drag ng-tns-c361-4 element cdk-drag-disabled ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell font-weight-bold titulo cursor-pointer cdk-column-tema mat-column-tema ng-tns-c361-4 ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c361-4&quot;]</value>
      <webElementGuid>b88e193e-48e9-434a-8c90-cd4dc05a6df4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>/html/body/aula-planeta-root/aula-planeta-main/div/div/div[1]/mat-sidenav-container/mat-sidenav-content/aula-planeta-materia/div/div[2]/aula-planeta-mis-temas/table/tbody/tr[13]/td[3]/span</value>
      <webElementGuid>470920a8-d3d1-4119-adf6-8d8a293cf1b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
