<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Copia profesor 1 (1)</name>
   <tag></tag>
   <elementGuidId>e0db5045-394d-4f68-9c78-6533658282b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cdk-drop-list-0']/tbody/tr[13]/td[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4317d726-1e23-46ee-9551-51ac7062cd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c337-4</value>
      <webElementGuid>37e6032f-a2bd-4901-beb7-47cc187e5b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copia profesor 1</value>
      <webElementGuid>a1b537f0-396d-43aa-a18b-735b00c64904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-0&quot;)/tbody[1]/tr[@class=&quot;mat-row cdk-row cdk-drag ng-tns-c337-4 element cdk-drag-disabled ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell font-weight-bold titulo cursor-pointer cdk-column-tema mat-column-tema ng-tns-c337-4 ng-star-inserted&quot;]/span[@class=&quot;ng-tns-c337-4&quot;]</value>
      <webElementGuid>5c522b38-558d-4eae-9093-73de7350c043</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cdk-drop-list-0']/tbody/tr[13]/td[3]/span</value>
      <webElementGuid>87a2964a-41fe-4363-b909-fd0b040a2fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enlaces de referencia'])[5]/following::span[4]</value>
      <webElementGuid>569a9ca3-6be1-439a-9cfd-e48a877dc4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fin de unidad: Repaso'])[6]/following::span[5]</value>
      <webElementGuid>ec9a220c-73b5-4708-b96e-e0da2c891c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introducción'])[7]/preceding::span[4]</value>
      <webElementGuid>b320ca25-d57e-4a91-95a5-a5afafc0bd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La nutrición y los tipos de alimentos'])[2]/preceding::span[5]</value>
      <webElementGuid>3312a601-cf99-4309-ad11-97254147a5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copia profesor 1']/parent::*</value>
      <webElementGuid>34147d8f-53f9-4e04-b974-d09219891412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[3]/span</value>
      <webElementGuid>1061df30-bf91-4913-bff5-0562e7d5a586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Copia profesor 1' or . = 'Copia profesor 1')]</value>
      <webElementGuid>a8638741-66b4-4cfc-aa4c-b70b046c21ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
