<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Copia profesor 1</name>
   <tag></tag>
   <elementGuidId>aa0736de-83e0-4fa0-801d-5714439d3fa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cdk-drop-list-0']/tbody/tr[13]/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Copia profesor 1' or . = 'Copia profesor 1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e499bc38-9aff-4f0e-acd5-5fab7d441c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>a1b0e8ce-55a3-454e-bebb-ff4807d383d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell font-weight-bold titulo cursor-pointer cdk-column-tema mat-column-tema ng-tns-c337-4 ng-star-inserted</value>
      <webElementGuid>06314062-c5ca-49b6-a6e5-cfa1fc526061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copia profesor 1</value>
      <webElementGuid>015664f0-e0fa-406c-9037-84b1e5f9262a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-drop-list-0&quot;)/tbody[1]/tr[@class=&quot;mat-row cdk-row cdk-drag ng-tns-c337-4 element cdk-drag-disabled ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell font-weight-bold titulo cursor-pointer cdk-column-tema mat-column-tema ng-tns-c337-4 ng-star-inserted&quot;]</value>
      <webElementGuid>1e5536d9-17e5-42b7-a0c8-91edca377721</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cdk-drop-list-0']/tbody/tr[13]/td[3]</value>
      <webElementGuid>5bb3c988-c56d-46f9-8641-8ebe30504e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enlaces de referencia'])[5]/following::td[3]</value>
      <webElementGuid>80254baa-9be3-4c73-87e1-7c6b8c29819c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fin de unidad: Repaso'])[6]/following::td[3]</value>
      <webElementGuid>64cd9621-0a22-43fe-872f-072fa817b3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introducción'])[7]/preceding::td[2]</value>
      <webElementGuid>d675c844-3690-4411-a142-67a4968c5883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[3]</value>
      <webElementGuid>3d6a1712-1d54-4682-9d68-064317e46309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Copia profesor 1' or . = 'Copia profesor 1')]</value>
      <webElementGuid>15064bc4-05a0-466e-a8a1-ec36a5c82031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
